### ISSUE TITLE
Embedded NNUE - Modifed Files

### ISSUE THREAD

**Issue by jimablett** [0mn1verze/Maestro-Chess-Engine#1]
Hi Evan,

Here are some modified src files so engine will load from embedded net.

https://drive.proton.me/urls/5B54RSYD84#MF9hNNanxJzJ

Do you have any plans to generate your own net instead of using Stockfish NNUE ?

I'd like to see Maestro compete in chess tournaments but it would need it's own NNUE.

regards,
Jim.

**Comment by Hin-Yu-Evan-Fung** [comment]
I have plans to create my own handcrafted evaluation function and a NNUE neural net, but I will have to spend some time to learn the architectures so that I can implement a custom net.

**Comment by Hin-Yu-Evan-Fung** [comment]
Thank you for suggesting the feature to load from embedded net instead of having a separate file, is there are reason for that?

**Comment by jimablett** [comment]
I think it's preferable if it's just a single executable with no extra files. It's also easier to use and more convenient that way on Android devices.
